- src/app.module.ts
- src/controllers/vcauthn/OobInvitationDto.ts
- src/controllers/vcauthn/PresentProofCreateDto.ts
- src/controllers/vcauthn/VCAuthNController.ts
- src/events/VCAuthnEvents.ts
- src/main.ts
Adding endpoints and events compatible with BC Gov [VC-AuthN OIDC](https://github.com/bcgov/vc-authn-oidc).
TODO: make it an optional module in order to make it isolated from other Service Agent features.
> feat: VC AuthN support

- .github/workflows/cd.yml
- .github/workflows/lint-pr.yml
- examples/demo-dts/package.json
- examples/demo-dts/src/app.module.ts
- examples/demo-dts/src/app.service.ts
- examples/demo-dts/yarn.lock
- packages/main/package.json
- packages/nestjs-client/package.json
Fixing nestjs-client package name to publish in NPM.
Also adding a PR title validation to prevent from pushing non-conventional commits to main-
> fix: nestjs client package name

- examples/chatbot/index.ts
- packages/main/package.json
- packages/main/src/events/MessageEvents.ts
- packages/model/package.json
- packages/model/src/messages/mrtd/EMrtdDataSubmitMessage.ts
- packages/model/src/messages/mrtd/MrzDataSubmitMessage.ts
- yarn.lock
feature:
- models: [handling state on mrtd](https://github.com/2060-io/2060-service-agent/pull/52/commits/db03cb46d142fe1bab70b88b9b8cce3dce96ca66)
- main: [handling event mrtd problem](https://github.com/2060-io/2060-service-agent/pull/52/commits/67467072551ca26e07dae3bb8db8799ecc9b5664)
- chatbot: [add refuse validation on chatbot](https://github.com/2060-io/2060-service-agent/pull/52/commits/586b0a06531c6f179debc17b1b2e9deadfa3accb)
> fix: handle problem report events for MRTD and improve state management on model

- packages/main/src/main.ts
> fix: enable cors

- packages/main/src/events/MessageEvents.ts
For some unfortunate reason, claims were not sent in presentation callbacks. Now we add them (if they exist).
-
> fix: send claims in presentation callback url

- packages/nestjs-client/package.json
- yarn.lock
> fix: nestjs-client dependencies

- examples/chatbot/index.ts
- examples/verifier/index.ts
- packages/client/README.md
- packages/client/src/ApiClient.ts
- packages/model/README.md
- packages/nestjs-client/README.md
- packages/nestjs-client/src/credentials/credential.service.ts
> feat: update docs and standardization of methods in ApiClient

- doc/service-agent-api.md
- packages/main/src/events/CallbackEvent.ts
- packages/main/src/events/ConnectionEvents.ts
**Related issue:** https://github.com/2060-io/unic.id-generic-verifier-dts/issues/9
-
> feat: add waiting state

- .github/workflows/cd.yml
- package.json
- packages/client/package.json
- packages/model/package.json
- packages/nestjs-client/package.json
> fix: Updated Yarn to v3.6.4 and updated CI/CD configuration file

- README.md
> docs: update redis and postgres improvement

- .github/workflows/cd.yml
- .github/workflows/stable-release.yml
- packages/nestjs-client/src/types.ts
> fix: add the correct version to variable service libraries

- .github/workflows/stable-release.yml
> ci: update steps.get_version.outputs.version and DEMO_CHATBOT_IMAGE_NAME

- .github/workflows/cd.yml
- .github/workflows/stable-release.yml
- examples/chatbot/package.json
- examples/phonenumbervs/package.json
- examples/verifier/package.json
- packages/client/package.json
- packages/main/package.json
- packages/model/package.json
- packages/nestjs-client/package.json
> fix: upload version

- .github/workflows/cd.yml
> fix: add no git check

- .github/workflows/cd.yml
- .github/workflows/stable-release.yml
> fix: update version for release

- charts/chatbot/Chart.yaml
> fix: add correct repository

- charts/chatbot/values.yaml
- charts/vs-agent/templates/deployment.yaml
- charts/vs-agent/values.yaml
> fix: add helm chart db to agent

- .github/workflows/cd.yml
> fix: add tag for demo chatbot

- examples/nestjs-vs/package.json
- examples/nestjs-vs/src/core.service.ts
- packages/nestjs-client/README.md
- pnpm-lock.yaml
> docs: add docs for vs-nestjs-client stats module

- charts/chatbot/templates/deployment.yaml
- charts/chatbot/values.yaml
- charts/vs-agent/templates/deployment.yaml
- charts/vs-agent/values.yaml
- examples/chatbot/Dockerfile
> fix: simplify charts

- charts/chatbot/templates/deployment.yaml
- charts/chatbot/values.yaml
> fix: solve problem on ingress chatbot demo

- .github/workflows/cd.yml
- .github/workflows/stable-release.yml
And also some improvements/fixes on the CI
Closes #146
> ci: add latest tags in Docker container images

- .github/workflows/cd.yml
- .github/workflows/stable-release.yml
- apps/vs-agent/package.json
> fix: vs-agent version

- apps/vs-agent/src/utils/VsAgent.ts
- examples/chatbot/docker-compose.yml
> fix: remove unused anoncreds URL

- .release-please-manifest.json
- release-please-config.json
based on https://github.com/puppeteer/puppeteer
> fix: release please

- release-please-config.json
> fix: update-release-please

- release-please-config.json
add based on https://github.com/googleapis/release-please/issues/2425 issue
> fix: add updateAllPackages

- release-please-config.json
> fix: remove node-workspace

- release-please-config.json
> fix: change components name

- .release-please-manifest.json
- package.json
- release-please-config.json
> fix: add root release please

- apps/vs-agent/src/controllers/public/self-tr/SelfTrController.ts
- apps/vs-agent/src/utils/setupAgent.ts
> fix: correct structure of self-signed DID document

- apps/vs-agent/package.json
- pnpm-lock.yaml
Update credo-ts-didcomm-mrtd version 0.0.15
> feat: Update credo-ts-didcomm-mrtd version 0.0.15

- apps/vs-agent/package.json
- packages/model/package.json
- packages/model/src/messages/mrtd/EMrtdDataSubmitMessage.ts
- packages/nestjs-client/package.json
- pnpm-lock.yaml
Add support for `verification` in EMrtdDataSubmitMessage, ensuring the field is included when instantiating messages.
> feat: add verification field to EMrtdDataSubmitMessage

- charts/chatbot/values.yaml
- charts/vs-agent/templates/deployment.yaml
- charts/vs-agent/values.yaml
Available port endpoint for admin access through a secure white list vpn endpoint for specific behavior
> fix: admin port for secure endpoint
